#!/usr/bin/env bun

/**
 * Generate the typed, baked-in copy of the Chrome extension's capability contract.
 *
 * Source of truth is the extension's `capabilities.json`. When the sibling
 * `xcsh-chrome-extension` repo is checked out (the ecosystem is built together),
 * its freshly-built `capabilities.json` is copied into the vendored location so the
 * two binaries ship the same contract; otherwise the committed vendored copy is
 * used (CI / standalone). The result is emitted as `capabilities.generated.ts` and
 * compiled into the xcsh binary.
 *
 *   bun scripts/generate-extension-capabilities.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";

const here = import.meta.dir; // packages/coding-agent/scripts
const vendoredPath = path.resolve(here, "../src/browser/capabilities.json");
const generatedPath = path.resolve(here, "../src/browser/capabilities.generated.ts");

// Co-build refresh: prefer the sibling extension's freshly-built contract.
const siblingPath =
	process.env.XCSH_EXTENSION_CAPABILITIES ?? path.resolve(here, "../../../../xcsh-chrome-extension/capabilities.json");
if (fs.existsSync(siblingPath) && path.resolve(siblingPath) !== vendoredPath) {
	fs.copyFileSync(siblingPath, vendoredPath);
}

const manifest = JSON.parse(fs.readFileSync(vendoredPath, "utf8")) as {
	contractVersion: string;
	tools: Array<{ name: string }>;
};
const toolNames = manifest.tools.map(t => t.name);

const output = [
	"// Auto-generated by scripts/generate-extension-capabilities.ts - DO NOT EDIT",
	"// Source: src/browser/capabilities.json (the Chrome extension's published contract).",
	"",
	"export interface ExtensionToolFlags {",
	"\treadonly readOnly?: boolean;",
	"\treadonly mutates?: boolean;",
	"\treadonly requiresExplainMode?: boolean;",
	"}",
	"",
	"export interface ExtensionToolDef {",
	"\treadonly name: string;",
	"\treadonly summary: string;",
	"\treadonly category: string;",
	"\treadonly params: Record<string, unknown>;",
	"\treadonly flags?: ExtensionToolFlags;",
	"}",
	"",
	"export interface ExtensionCapabilities {",
	"\treadonly version: string;",
	"\treadonly contractVersion: string;",
	"\treadonly multiPortDiscovery?: boolean;",
	"\treadonly protocol: string;",
	"\treadonly tools: readonly ExtensionToolDef[];",
	"\treadonly features: Record<string, unknown>;",
	"}",
	"",
	`export const EXTENSION_CAPABILITIES: ExtensionCapabilities = ${JSON.stringify(manifest, null, "\t")};`,
	"",
	`export const EXTENSION_CONTRACT_VERSION = ${JSON.stringify(manifest.contractVersion)};`,
	"",
	`export const EXTENSION_TOOL_NAMES: readonly string[] = ${JSON.stringify(toolNames)};`,
	"",
].join("\n");

await Bun.write(generatedPath, output);
console.log(
	`Generated ${path.relative(process.cwd(), generatedPath)} (${toolNames.length} tools, contract ${manifest.contractVersion})`,
);
