#!/usr/bin/env bun

/**
 * Generate the typed, baked-in copy of the Chrome extension's capability contract.
 *
 * Source of truth is the extension's `capabilities.json`. When the sibling
 * `xcsh-chrome-extension` repo is checked out (the ecosystem is built together),
 * its freshly-built `capabilities.json` is copied into the vendored location so the
 * two binaries ship the same contract; otherwise the committed vendored copy is
 * used (CI / standalone). The result is emitted as `capabilities.generated.ts` and
 * compiled into the xcsh binary.
 *
 *   bun scripts/generate-extension-capabilities.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";

const here = import.meta.dir; // packages/coding-agent/scripts
const vendoredPath = path.resolve(here, "../src/browser/capabilities.json");
const generatedPath = path.resolve(here, "../src/browser/capabilities.generated.ts");

// Guarded so the regression checks below can be imported by tests without regenerating files.
// Importing this module used to run the whole generator as a side effect (#2578).
if (import.meta.main) {
	// Co-build refresh: adopt the sibling extension's freshly-built contract — but only when it really is
	// fresher. "The directory exists" is not evidence of that, and treating it as evidence silently rewrote a
	// committed contract from whatever happened to be on the developer's disk (#2578).
	//
	// Measured on a real machine: a sibling checkout left at contractVersion 1.8.0 overwrote the committed
	// 1.12.0 and deleted the whole `handshake` feature block, on every `bun run check`, `bun test` and
	// `bun run build`. `release.ts` runs `git commit -a`, so the downgrade was one release away from shipping.
	const siblingPath =
		process.env.XCSH_EXTENSION_CAPABILITIES ??
		path.resolve(here, "../../../../xcsh-chrome-extension/capabilities.json");
	if (fs.existsSync(siblingPath) && path.resolve(siblingPath) !== vendoredPath) {
		adoptSiblingIfNotARegression(siblingPath, vendoredPath);
	}

	const manifest = JSON.parse(fs.readFileSync(vendoredPath, "utf8")) as {
		contractVersion: string;
		tools: Array<{ name: string }>;
	};
	const toolNames = manifest.tools.map(t => t.name);

	const output = [
		"// Auto-generated by scripts/generate-extension-capabilities.ts - DO NOT EDIT",
		"// Source: src/browser/capabilities.json (the Chrome extension's published contract).",
		"",
		"export interface ExtensionToolFlags {",
		"\treadonly readOnly?: boolean;",
		"\treadonly mutates?: boolean;",
		"\treadonly requiresExplainMode?: boolean;",
		"}",
		"",
		"export interface ExtensionToolDef {",
		"\treadonly name: string;",
		"\treadonly summary: string;",
		"\treadonly category: string;",
		"\treadonly params: Record<string, unknown>;",
		"\treadonly flags?: ExtensionToolFlags;",
		"}",
		"",
		"export interface ExtensionCapabilities {",
		"\treadonly version: string;",
		"\treadonly contractVersion: string;",
		"\treadonly multiPortDiscovery?: boolean;",
		"\treadonly protocol: string;",
		"\treadonly tools: readonly ExtensionToolDef[];",
		"\treadonly features: Record<string, unknown>;",
		"}",
		"",
		`export const EXTENSION_CAPABILITIES: ExtensionCapabilities = ${JSON.stringify(manifest, null, "\t")};`,
		"",
		`export const EXTENSION_CONTRACT_VERSION = ${JSON.stringify(manifest.contractVersion)};`,
		"",
		`export const EXTENSION_TOOL_NAMES: readonly string[] = ${JSON.stringify(toolNames)};`,
		"",
	].join("\n");

	await Bun.write(generatedPath, output);
	console.log(
		`Generated ${path.relative(process.cwd(), generatedPath)} (${toolNames.length} tools, contract ${manifest.contractVersion})`,
	);
}

/** A capability manifest, as far as the regression check needs to understand one. */
interface CapabilityManifest {
	contractVersion?: string;
	tools?: Array<{ name?: string }>;
	features?: Record<string, unknown>;
}

/**
 * Decide whether a sibling manifest may replace the committed one.
 *
 * Exported for tests. Returns the reason to refuse, or undefined when adoption is safe.
 *
 * Two independent guards, because they catch different mistakes:
 *  - a lower `contractVersion` is a stale checkout, the case that actually happened;
 *  - a missing tool or feature key at the same-or-higher version is a broken build, which a version
 *    comparison alone would wave through.
 */
export function regressionReason(sibling: CapabilityManifest, vendored: CapabilityManifest): string | undefined {
	const siblingVersion = sibling.contractVersion ?? "";
	const vendoredVersion = vendored.contractVersion ?? "";
	if (compareContractVersions(siblingVersion, vendoredVersion) < 0) {
		return `contractVersion would go backwards, ${vendoredVersion} -> ${siblingVersion}`;
	}

	const lostTools = missingKeys(
		(vendored.tools ?? []).map(tool => tool.name ?? ""),
		(sibling.tools ?? []).map(tool => tool.name ?? ""),
	);
	if (lostTools.length > 0) return `tools would be lost: ${lostTools.join(", ")}`;

	const lostFeatures = missingKeys(Object.keys(vendored.features ?? {}), Object.keys(sibling.features ?? {}));
	if (lostFeatures.length > 0) return `features would be lost: ${lostFeatures.join(", ")}`;

	return undefined;
}

function missingKeys(expected: readonly string[], actual: readonly string[]): string[] {
	const present = new Set(actual.filter(Boolean));
	return expected.filter(key => key !== "" && !present.has(key));
}

/** Numeric-segment comparison. Enough for a dotted contract version, and no dependency. */
export function compareContractVersions(left: string, right: string): number {
	const parse = (value: string): number[] => value.split(".").map(part => Number.parseInt(part, 10) || 0);
	const a = parse(left);
	const b = parse(right);
	for (let index = 0; index < Math.max(a.length, b.length); index += 1) {
		const diff = (a[index] ?? 0) - (b[index] ?? 0);
		if (diff !== 0) return diff < 0 ? -1 : 1;
	}
	return 0;
}

function adoptSiblingIfNotARegression(from: string, to: string): void {
	let sibling: CapabilityManifest;
	let vendored: CapabilityManifest;
	try {
		sibling = JSON.parse(fs.readFileSync(from, "utf8")) as CapabilityManifest;
		vendored = JSON.parse(fs.readFileSync(to, "utf8")) as CapabilityManifest;
	} catch (error) {
		// Unreadable input must not silently leave the committed copy in place either — say so.
		console.warn(`Keeping the committed capabilities: could not compare with ${from} (${String(error)}).`);
		return;
	}

	const reason = regressionReason(sibling, vendored);
	if (reason === undefined) {
		fs.copyFileSync(from, to);
		return;
	}

	// Refused rather than fatal: this generator runs from `check:types`, `test` and `build`, so failing
	// here would block every command on any machine with a stale sibling checkout. Skipping keeps the
	// committed contract — the correct one — and names what was ignored so it is fixable.
	console.warn(
		`Ignoring ${from}: ${reason}.\n` +
			"  The committed capabilities.json is being kept. Update or remove that checkout, or set\n" +
			"  XCSH_EXTENSION_CAPABILITIES to the manifest you actually want compiled in.",
	);
}
