#!/usr/bin/env bun

import * as path from "node:path";
import { $ } from "bun";
import {
	type EnvLike,
	resolveBranch,
	resolveCommit,
	resolveDirty,
	resolvePrNumber,
	resolveTag,
} from "./build-info/resolvers";

const repoRoot = path.resolve(import.meta.dir, "../../..");
const outputPath = path.resolve(import.meta.dir, "../src/internal-urls/build-info.generated.ts");
const utilsPackageJsonPath = path.resolve(repoRoot, "packages/utils/package.json");

const REPO_SLUG = "f5-sales-demo/xcsh";
const REPO_URL = `https://github.com/${REPO_SLUG}`;

async function git(args: string[]): Promise<string> {
	try {
		const result = await $`git ${args}`.cwd(repoRoot).quiet();
		return result.stdout.toString().trim();
	} catch {
		return "";
	}
}

async function ghPrForSha(sha: string): Promise<string> {
	try {
		const result =
			await $`gh pr list --search ${sha} --state merged --json number --limit 1 --jq ${".[0].number // empty"}`
				.cwd(repoRoot)
				.quiet();
		return result.stdout.toString().trim();
	} catch {
		return "";
	}
}

async function resolveCommitDate(sha: string): Promise<string> {
	if (!sha) return "";
	return await git(["log", "-1", "--format=%cI", sha]);
}

const env = process.env as EnvLike;

const utilsPackageJson = (await Bun.file(utilsPackageJsonPath).json()) as { version: string };
const version = utilsPackageJson.version;
const commit = await resolveCommit(env, git);
const shortCommit = commit ? commit.slice(0, 7) : "";
const branch = await resolveBranch(env, git);
const tag = await resolveTag(env, git);
const commitDate = await resolveCommitDate(commit);
const dirty = await resolveDirty(env, git);
const prNumber = await resolvePrNumber(commit, env, ghPrForSha);
const buildDate = new Date().toISOString();
const releaseUrl = `${REPO_URL}/releases/tag/v${version}`;
const commitUrl = commit ? `${REPO_URL}/commit/${commit}` : REPO_URL;

const output = [
	"// Auto-generated by scripts/generate-build-info.ts - DO NOT EDIT",
	"",
	"export interface BuildInfo {",
	"\treadonly version: string;",
	"\treadonly commit: string;",
	"\treadonly shortCommit: string;",
	"\treadonly branch: string;",
	"\treadonly tag: string;",
	"\treadonly commitDate: string;",
	"\treadonly buildDate: string;",
	"\treadonly dirty: boolean;",
	"\treadonly prNumber: string;",
	"\treadonly repoUrl: string;",
	"\treadonly repoSlug: string;",
	"\treadonly commitUrl: string;",
	"\treadonly releaseUrl: string;",
	"}",
	"",
	`export const BUILD_INFO: BuildInfo = ${JSON.stringify(
		{
			version,
			commit,
			shortCommit,
			branch,
			tag,
			commitDate,
			buildDate,
			dirty,
			prNumber,
			repoUrl: REPO_URL,
			repoSlug: REPO_SLUG,
			commitUrl,
			releaseUrl,
		},
		null,
		"\t",
	)};`,
	"",
].join("\n");

await Bun.write(outputPath, output);
console.log(
	`Generated ${path.relative(process.cwd(), outputPath)} (v${version}, ${shortCommit || "no-commit"}, branch=${branch}${tag ? `, tag=${tag}` : ""}${dirty ? ", dirty" : ""})`,
);
