#!/usr/bin/env bun
// scripts/generate-console-field-metadata.ts
//
// Embeds the console field-requirements registry from the authoritative source
// (api-specs-enriched/config/console_field_metadata.yaml) into
// src/internal-urls/console-field-metadata.generated.ts. Mirrors the source
// resolution of generate-api-spec-index.ts (env override → sibling checkout).
// The registry is what `xcsh://console/<resource>` surfaces so the agent knows
// each form's required fields + constraints before driving a create workflow.
//
// If api-specs-enriched is missing/incorrect field metadata, fix it UPSTREAM
// there and re-run this — never hand-edit the generated file or patch downstream.

import * as fs from "node:fs";
import * as path from "node:path";
import { parse as parseYaml } from "yaml";

const repoRoot = path.resolve(import.meta.dir, "..");
const outputPath = path.join(repoRoot, "src/internal-urls/console-field-metadata.generated.ts");

/** Resolve the console_field_metadata.yaml path from api-specs-enriched. */
function resolveMetadataFile(): string | null {
	const candidates = [
		process.env.API_SPECS_ENRICHED_DIR &&
			path.join(process.env.API_SPECS_ENRICHED_DIR, "config/console_field_metadata.yaml"),
		// Local sibling checkout: <workspace>/api-specs-enriched
		path.resolve(repoRoot, "../../../api-specs-enriched/config/console_field_metadata.yaml"),
		path.resolve(repoRoot, "../../../../api-specs-enriched/config/console_field_metadata.yaml"),
	].filter(Boolean) as string[];
	for (const c of candidates) {
		if (fs.existsSync(c)) return c;
	}
	return null;
}

function build(): { version: string; resources: Record<string, Record<string, unknown>> } {
	const file = resolveMetadataFile();
	if (!file) {
		console.warn("api-specs-enriched console_field_metadata.yaml not found; emitting empty registry");
		return { version: "unavailable", resources: {} };
	}
	const doc = (parseYaml(fs.readFileSync(file, "utf-8")) ?? {}) as {
		version?: string;
		resources?: Record<string, Record<string, unknown> | null>;
	};
	const resources: Record<string, Record<string, unknown>> = {};
	for (const [kind, fields] of Object.entries(doc.resources ?? {})) {
		if (fields && typeof fields === "object") resources[kind] = fields as Record<string, unknown>;
	}
	const version = process.env.API_SPECS_ENRICHED_VERSION ?? doc.version ?? "local";
	return { version, resources };
}

const data = build();

// Keep the committed registry if the source wasn't found and a file already exists.
if (data.version === "unavailable" && fs.existsSync(outputPath)) {
	console.log("console field metadata source not found; keeping existing generated module");
	process.exit(0);
}

const output = [
	"// Auto-generated by scripts/generate-console-field-metadata.ts - DO NOT EDIT",
	"// Source of truth: api-specs-enriched/config/console_field_metadata.yaml",
	"",
	`import type { ConsoleFieldMetadataData } from "./console-field-metadata-types";`,
	"",
	`export const CONSOLE_FIELD_METADATA: ConsoleFieldMetadataData = ${JSON.stringify(data, null, 2)};`,
	"",
].join("\n");

await Bun.write(outputPath, output);
const total = Object.values(data.resources).reduce((n, f) => n + Object.keys(f).length, 0);
console.log(`Wrote ${outputPath} (resources=${Object.keys(data.resources).length}, fields=${total})`);
