#!/usr/bin/env bun

import { Database } from "bun:sqlite";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { gzipSync } from "node:zlib";
import { createStore } from "@tobilu/qmd";
import {
	buildApiCatalogDiscoveryCorpus,
	fingerprintApiCatalogDiscoveryCorpus,
} from "../src/internal-urls/api-catalog-discovery";
import { API_CATALOG_DATA, API_CATALOG_INDEX } from "../src/internal-urls/api-catalog-index.generated";
import { insertApiQmdDocuments } from "./api-qmd-documents";
import { assertSourceRecord, requireFreshCorpusSources } from "./corpus-sources";

const specPin = JSON.parse(await readFile(path.join(import.meta.dir, "../../../tools/spec-release.json"), "utf8")) as {
	version: string;
	target_commit: string;
	release_tag: string;
	assets: Record<string, string>;
};
const sources = await requireFreshCorpusSources();
assertSourceRecord(sources.api, specPin);
if (specPin.version !== API_CATALOG_INDEX.version || !/^[a-f0-9]{40}$/.test(specPin.target_commit))
	throw new Error("API catalog discovery source disagrees with reviewed release pin");
const sourceSha = specPin.target_commit;
const qmdVersion = "2.8.3";
const outputPath = path.join(import.meta.dir, "../src/internal-urls/api-catalog-qmd-index.generated.ts");

function sha256(bytes: Uint8Array): string {
	return createHash("sha256").update(bytes).digest("hex");
}

function canonicalizeSqliteMetadata(databasePath: string): void {
	const database = new Database(databasePath);
	try {
		database.exec("PRAGMA secure_delete = ON");
		database.exec("BEGIN");
		database.prepare("UPDATE content SET created_at = ?").run("2000-01-01T00:00:00.000Z");
		database
			.prepare("UPDATE documents SET created_at = ?, modified_at = ?")
			.run("2000-01-01T00:00:00.000Z", "2000-01-01T00:00:00.000Z");
		database.prepare("UPDATE store_collections SET path = ?").run("/xcsh-api-catalog");
		database.exec("DELETE FROM store_config");
		database.exec("COMMIT");
		database.exec("VACUUM");
	} finally {
		database.close();
	}
}

const corpus = buildApiCatalogDiscoveryCorpus(API_CATALOG_INDEX, API_CATALOG_DATA);
const fingerprint = fingerprintApiCatalogDiscoveryCorpus(corpus, sourceSha, `@tobilu/qmd@${qmdVersion}`);
const stagingRoot = await mkdtemp(path.join(os.tmpdir(), "xcsh-qmd-index-"));
const documentsRoot = path.join(stagingRoot, "documents");
const databasePath = path.join(stagingRoot, "index.sqlite");

try {
	await mkdir(documentsRoot, { recursive: true });
	const store = await createStore({
		dbPath: databasePath,
		config: { collections: { catalog: { path: documentsRoot, pattern: "*.md" } } },
	});
	try {
		insertApiQmdDocuments(store, corpus.documents);
		store.internal.db.exec("PRAGMA wal_checkpoint(TRUNCATE)");
		store.internal.db.exec("PRAGMA journal_mode = DELETE");
	} finally {
		await store.close();
	}
	canonicalizeSqliteMetadata(databasePath);
	const sqlite = await readFile(databasePath);
	sqlite.writeUInt32BE(1, 24);
	sqlite.writeUInt32BE(1, 92);
	sqlite.writeUInt32BE(3_000_000, 96);
	const gzip = gzipSync(sqlite);
	gzip[9] = 255;
	const generated = [
		"// Generated by scripts/generate-api-catalog-qmd-index.ts. Do not edit.",
		"export const QMD_API_CATALOG_PREBUILT_INDEX = {",
		`\tsourceVersion: ${JSON.stringify(API_CATALOG_INDEX.version)},`,
		`\tfingerprint: ${JSON.stringify(fingerprint)},`,
		`\tsqliteSha256: ${JSON.stringify(sha256(sqlite))},`,
		"\tgzipBase64:",
		`\t\t${JSON.stringify(gzip.toString("base64"))},`,
		"} as const;",
		"",
	].join("\n");
	await writeFile(outputPath, generated, "utf8");
	console.log(
		`Generated ${path.relative(process.cwd(), outputPath)} (${sqlite.length} SQLite bytes, ${gzip.length} gzip bytes)`,
	);
} finally {
	await rm(stagingRoot, { recursive: true, force: true });
}
