#!/usr/bin/env bun
/**
 * Pre-compute the HTML template at publish time.
 * This avoids the Bun macro restriction in node_modules.
 */

import { TEMML_CSS } from "../../chat-ui/src/markdown/temml-css.generated";

const dir = new URL("../src/export/html/", import.meta.url).pathname;
const mathEntry = new URL("../../chat-ui/src/markdown/math.browser.ts", import.meta.url).pathname;

// Read all files
const html = await Bun.file(`${dir}template.html`).text();
const css = await Bun.file(`${dir}template.css`).text();
const js = await Bun.file(`${dir}template.js`).text();
const marked = await Bun.file(`${dir}vendor/marked.min.js`).text();
const highlight = await Bun.file(`${dir}vendor/highlight.min.js`).text();

const mathBuild = await Bun.build({
	entrypoints: [mathEntry],
	target: "browser",
	format: "iife",
	minify: true,
});
if (!mathBuild.success || mathBuild.outputs.length !== 1) {
	throw new AggregateError(mathBuild.logs, "Failed to bundle the shared browser math renderer");
}
const math = await mathBuild.outputs[0].text();

// Minify CSS
const minifiedCss = css
	.replace(/\/\*[\s\S]*?\*\//g, "")
	.replace(/\s+/g, " ")
	.replace(/\s*([{}:;,])\s*/g, "$1")
	.trim();

const escapeInlineScript = (source: string): string => source.replace(/<\/script/gi, "<\\/script");

// Inline everything
const template = html
	.replace("<template-css/>", () => `<style>${minifiedCss}</style><style>${TEMML_CSS}</style>`)
	.replace("<template-vendor-js/>", () => `<script>${escapeInlineScript(`${marked}\n${highlight}\n${math}`)}</script>`)
	.replace("<template-js/>", () => `<script>${escapeInlineScript(js)}</script>`);

// Write generated file
const output = `// Auto-generated by scripts/generate-template.ts - DO NOT EDIT
export const TEMPLATE = ${JSON.stringify(template)};
`;

await Bun.write(`${dir}template.generated.ts`, output);
console.log("Generated template.generated.ts");
