#!/usr/bin/env bun

import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { gzipSync } from "node:zlib";
import {
	buildDocumentationIndex,
	DOCUMENTATION_RELEASE_ASSETS,
	parseDocumentationReleasePin,
	sha256Bytes,
	verifyDocumentationRelease,
	verifyPrebuiltDocumentationAssets,
} from "../src/internal-urls/documentation-snapshot";

const repoRoot = path.join(import.meta.dir, "../../..");
const pinPath = path.join(repoRoot, "tools", "documentation-release.json");
const generatedRoot = path.join(import.meta.dir, "../src/internal-urls/.documentation-generated");
const loaderPath = path.join(import.meta.dir, "../src/internal-urls/documentation-assets.generated.ts");
const placeholder = [
	"// Generated by scripts/generate-documentation-index.ts for compiled builds. Do not edit.",
	'import type { EmbeddedDocumentationAssets } from "./documentation-repository";',
	"export const EMBEDDED_DOCUMENTATION_ASSETS: EmbeddedDocumentationAssets | null = null;",
	"",
].join("\n");

interface EmbeddedIndexMetadata {
	releaseTag: string;
	sourceCommit: string;
	archiveSha256: string;
	archiveSizeBytes: number;
	indexSha256: string;
	indexSizeBytes: number;
	fingerprint: string;
	documentCount: number;
	assetCount: number;
	textManifestSha256?: string;
	bundledAssetCount?: number;
}

function deterministicGzip(bytes: Uint8Array): Buffer {
	const compressed = gzipSync(bytes, { level: 9 });
	// RFC 1952 permits 255 for an unknown originating OS. Canonicalize it so
	// release builds on different hosts embed byte-identical content.
	compressed[9] = 255;
	return compressed;
}

function argument(name: string): string | undefined {
	const index = process.argv.indexOf(name);
	return index < 0 ? undefined : process.argv[index + 1];
}

async function downloadRelease(root: string, repository: string, tag: string): Promise<void> {
	await mkdir(root, { recursive: true });
	for (const name of DOCUMENTATION_RELEASE_ASSETS) {
		const url = `https://github.com/${repository}/releases/download/${encodeURIComponent(tag)}/${encodeURIComponent(name)}`;
		const response = await fetch(url, { redirect: "follow" });
		if (!response.ok || !response.body) throw new Error(`failed to download ${name}: HTTP ${response.status}`);
		await Bun.write(path.join(root, name), response.body);
	}
}

async function writeLoader(indexGzip: Uint8Array, metadata: EmbeddedIndexMetadata): Promise<void> {
	const generated = [
		"// Generated by scripts/generate-documentation-index.ts for compiled builds. Do not edit.",
		'import indexGzipPath from "./.documentation-generated/documentation-index.sqlite.gz" with { type: "file" };',
		'import type { EmbeddedDocumentationAssets } from "./documentation-repository";',
		"export const EMBEDDED_DOCUMENTATION_ASSETS = {",
		"\tindexGzipPath,",
		`\tindexGzipSha256: ${JSON.stringify(sha256Bytes(indexGzip))},`,
		`\tindexGzipSizeBytes: ${indexGzip.byteLength},`,
		`\treleaseTag: ${JSON.stringify(metadata.releaseTag)},`,
		`\tsourceCommit: ${JSON.stringify(metadata.sourceCommit)},`,
		`\tarchiveSha256: ${JSON.stringify(metadata.archiveSha256)},`,
		`\tarchiveSizeBytes: ${metadata.archiveSizeBytes},`,
		`\tindexSha256: ${JSON.stringify(metadata.indexSha256)},`,
		`\tindexSizeBytes: ${metadata.indexSizeBytes},`,
		`\tfingerprint: ${JSON.stringify(metadata.fingerprint)},`,
		`\tdocumentCount: ${metadata.documentCount},`,
		`\tassetCount: ${metadata.assetCount},`,
		`\ttextManifestSha256: ${JSON.stringify(metadata.textManifestSha256 ?? null)},`,
		`\tbundledAssetCount: ${metadata.bundledAssetCount ?? metadata.assetCount},`,
		"} as const satisfies EmbeddedDocumentationAssets;",
		"",
	].join("\n");
	await writeFile(loaderPath, generated, "utf8");
}

async function useExisting(pin: ReturnType<typeof parseDocumentationReleasePin>): Promise<void> {
	const { indexGzip } = await verifyPrebuiltDocumentationAssets(generatedRoot, pin);
	await writeLoader(indexGzip, {
		releaseTag: pin.release_tag,
		sourceCommit: pin.source_commit,
		archiveSha256: pin.assets["html-to-markdown-content.tar.gz"].sha256,
		archiveSizeBytes: pin.assets["html-to-markdown-content.tar.gz"].size_bytes,
		indexSha256: pin.index.sha256,
		indexSizeBytes: pin.index.size_bytes,
		fingerprint: pin.index.fingerprint,
		documentCount: pin.manifest.document_count,
		assetCount: pin.manifest.asset_count,
		textManifestSha256: pin.packaging?.text_manifest_sha256,
		bundledAssetCount: pin.packaging?.bundled_media_count,
	});
	console.log(
		JSON.stringify({
			fingerprint: pin.index.fingerprint,
			sha256: pin.index.sha256,
			sizeBytes: pin.index.size_bytes,
		}),
	);
}

async function generate(): Promise<void> {
	if (process.argv.includes("--reset")) {
		await rm(path.join(generatedRoot, "html-to-markdown-content.tar.gz"), { force: true });
		await rm(path.join(generatedRoot, "documentation-index.sqlite.gz"), { force: true });
		await writeFile(loaderPath, placeholder, "utf8");
		console.log("Reset embedded documentation assets.");
		return;
	}

	const rawPin = JSON.parse(await readFile(pinPath, "utf8"));
	const pin = parseDocumentationReleasePin(rawPin);
	if (process.argv.includes("--use-existing")) {
		if (process.argv.includes("--update-pin") || argument("--input-dir")) {
			throw new Error("--use-existing cannot be combined with --update-pin or --input-dir");
		}
		await useExisting(pin);
		return;
	}
	const supplied = argument("--input-dir");
	const downloadRoot = supplied ?? (await mkdtemp(path.join(os.tmpdir(), "xcsh-documentation-release-")));
	const ownsDownloadRoot = supplied === undefined;
	try {
		if (!supplied) await downloadRelease(downloadRoot, pin.source_repository, pin.release_tag);
		const snapshot = await verifyDocumentationRelease(downloadRoot, pin);
		const firstRoot = await mkdtemp(path.join(os.tmpdir(), "xcsh-documentation-build-a-"));
		const secondRoot = await mkdtemp(path.join(os.tmpdir(), "xcsh-documentation-build-b-"));
		try {
			const updatePin = process.argv.includes("--update-pin");
			const firstPath = path.join(firstRoot, "documentation-index.sqlite");
			const secondPath = path.join(secondRoot, "documentation-index.sqlite");
			const first = await buildDocumentationIndex(snapshot, firstPath);
			const second = await buildDocumentationIndex(snapshot, secondPath);
			if (JSON.stringify(first) !== JSON.stringify(second)) {
				throw new Error(`documentation index metadata is not deterministic: ${JSON.stringify({ first, second })}`);
			}
			if (!Buffer.from(await readFile(firstPath)).equals(await readFile(secondPath)))
				throw new Error("documentation SQLite bytes are not deterministic");
			const compressedIndex = deterministicGzip(await readFile(firstPath));
			const secondCompressedIndex = deterministicGzip(await readFile(secondPath));
			if (!compressedIndex.equals(secondCompressedIndex)) {
				throw new Error("compressed documentation SQLite bytes are not deterministic");
			}
			if (!updatePin && pin.index.fingerprint !== "pending" && pin.index.fingerprint !== first.fingerprint)
				throw new Error("documentation index fingerprint disagrees with pin");
			if (!updatePin && pin.index.sha256 !== "pending" && pin.index.sha256 !== first.sha256)
				throw new Error("documentation index digest disagrees with pin");
			if (!updatePin && pin.index.size_bytes !== 0 && pin.index.size_bytes !== first.sizeBytes)
				throw new Error("documentation index size disagrees with pin");

			if (process.argv.includes("--verify-only")) {
				console.log(JSON.stringify(first));
				return;
			}
			await mkdir(generatedRoot, { recursive: true });
			await rm(path.join(generatedRoot, "html-to-markdown-content.tar.gz"), { force: true });
			await writeFile(path.join(generatedRoot, "documentation-index.sqlite.gz"), compressedIndex, { mode: 0o600 });
			await writeLoader(compressedIndex, {
				releaseTag: snapshot.releaseTag,
				sourceCommit: snapshot.sourceCommit,
				archiveSha256: snapshot.archiveSha256,
				archiveSizeBytes: pin.assets["html-to-markdown-content.tar.gz"].size_bytes,
				indexSha256: first.sha256,
				indexSizeBytes: first.sizeBytes,
				fingerprint: first.fingerprint,
				documentCount: snapshot.documents.length,
				assetCount: snapshot.assets.length,
				textManifestSha256: pin.packaging?.text_manifest_sha256,
				bundledAssetCount: pin.packaging?.bundled_media_count,
			});
			if (updatePin) {
				rawPin.index = {
					qmd_version: "2.8.3",
					fingerprint: first.fingerprint,
					sha256: first.sha256,
					size_bytes: first.sizeBytes,
				};
				await writeFile(pinPath, `${JSON.stringify(rawPin, null, "\t")}\n`, "utf8");
			}
			console.log(JSON.stringify(first));
		} finally {
			await rm(firstRoot, { recursive: true, force: true });
			await rm(secondRoot, { recursive: true, force: true });
		}
	} finally {
		if (ownsDownloadRoot) await rm(downloadRoot, { recursive: true, force: true });
	}
}

await generate();
