#!/usr/bin/env bun
// scripts/generate-console-catalog.ts
import * as fs from "node:fs";
import * as path from "node:path";
import { sanitizePublicIpv4Examples } from "./sanitize-generated-content";

const repoRoot = path.resolve(import.meta.dir, "..");
const outputPath = path.join(repoRoot, "src/internal-urls/console-catalog.generated.ts");

/**
 * The catalog is captured from a live console, so it carries whatever tenant the operator who
 * captured it was signed in to — typically a personal staging tenant named after them. That is a
 * real identifier and must not be committed to a public repository (#2659). Rewrite it at the write
 * site so a re-capture cannot reintroduce it.
 */
function sanitizeTenantHosts(text: string): string {
	return (
		text
			.replace(/\b[a-z0-9][a-z0-9-]*\.staging\.volterra\.us\b/gi, "example.staging.volterra.us")
			// Catalog prose names the tenant too ("on the live <name> staging tenant"). Matched by shape
			// rather than by the person's name, so this file never has to carry the identifier it removes.
			.replace(/\b(?!example\b)[A-Za-z][\w.-]*(?=\s+staging\s+tenant\b)/g, "example")
	);
}

function resolveCatalogRoot(): { root: string; version: string } | null {
	const fromEnv = process.env.CONSOLE_CATALOG_DIR;
	if (fromEnv && fs.existsSync(path.join(fromEnv, "catalog"))) {
		return { root: fromEnv, version: process.env.CONSOLE_CATALOG_VERSION ?? "local" };
	}
	// Local sibling checkout: <workspace>/console
	const sibling = path.resolve(repoRoot, "../../../console");
	if (fs.existsSync(path.join(sibling, "catalog"))) {
		return { root: sibling, version: process.env.CONSOLE_CATALOG_VERSION ?? "local" };
	}
	return null;
}

function readYamlDir(dir: string, keyFn: (rel: string) => string): Record<string, string> {
	const out: Record<string, string> = {};
	if (!fs.existsSync(dir)) return out;
	const walk = (d: string) => {
		for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
			const full = path.join(d, entry.name);
			if (entry.isDirectory()) walk(full);
			else if (entry.name.endsWith(".yaml")) {
				const rel = path.relative(dir, full).replace(/\.yaml$/, "");
				out[keyFn(rel)] = fs.readFileSync(full, "utf-8");
			}
		}
	};
	walk(dir);
	// Sort keys for deterministic output regardless of readdir order.
	return Object.fromEntries(
		Object.keys(out)
			.sort()
			.map(k => [k, out[k]]),
	);
}

function build(): {
	version: string;
	workflows: Record<string, string>;
	resources: Record<string, string>;
	routes: Record<string, string>;
	navigation: string | null;
} {
	const resolved = resolveCatalogRoot();
	if (!resolved) {
		console.warn("console catalogue source not found; emitting empty catalogue");
		return { version: "unavailable", workflows: {}, resources: {}, routes: {}, navigation: null };
	}
	const { root, version } = resolved;
	const catalog = path.join(root, "catalog");
	// workflows keyed "<resource>/<operation>" (directory/file)
	const workflows = readYamlDir(path.join(catalog, "workflows"), rel => rel.split(path.sep).join("/"));
	// resources/routes keyed by basename id
	const resources = readYamlDir(path.join(catalog, "resources"), rel => path.basename(rel));
	const routes = readYamlDir(path.join(catalog, "routes"), rel => path.basename(rel));
	const navPath = path.join(catalog, "navigation/console-tree.yaml");
	const navigation = fs.existsSync(navPath) ? fs.readFileSync(navPath, "utf-8") : null;
	return { version, workflows, resources, routes, navigation };
}

const data = build();

// Fix A: when the source was not found AND the output file already exists,
// keep the committed catalogue rather than overwriting it with empty data.
if (data.version === "unavailable" && fs.existsSync(outputPath)) {
	console.log("console catalogue source not found; keeping existing generated module");
	process.exit(0);
}

const output = [
	"// Auto-generated by scripts/generate-console-catalog.ts - DO NOT EDIT",
	"",
	`import type { ConsoleCatalogData } from "./console-catalog-types";`,
	"",
	`export const CONSOLE_CATALOG_VERSION = ${JSON.stringify(data.version)};`,
	"",
	`export const CONSOLE_CATALOG_DATA: ConsoleCatalogData = ${JSON.stringify(data, null, 2)};`,
	"",
].join("\n");

await Bun.write(outputPath, sanitizePublicIpv4Examples(sanitizeTenantHosts(output)));
console.log(
	`Wrote ${outputPath} (workflows=${Object.keys(data.workflows).length}, resources=${Object.keys(data.resources).length})`,
);
