#!/usr/bin/env bun
// scripts/generate-console-catalog.ts
import * as fs from "node:fs";
import * as path from "node:path";

const repoRoot = path.resolve(import.meta.dir, "..");
const outputPath = path.join(repoRoot, "src/internal-urls/console-catalog.generated.ts");

function resolveCatalogRoot(): string | null {
	const fromEnv = process.env.CONSOLE_CATALOG_DIR;
	if (fromEnv && fs.existsSync(path.join(fromEnv, "catalog"))) return fromEnv;
	// Local sibling checkout: <workspace>/console
	const sibling = path.resolve(repoRoot, "../../../console");
	if (fs.existsSync(path.join(sibling, "catalog"))) return sibling;
	// TODO(P2): add release-artifact download mirroring generate-api-spec-index.ts.
	return null;
}

function readYamlDir(dir: string, keyFn: (rel: string) => string): Record<string, string> {
	const out: Record<string, string> = {};
	if (!fs.existsSync(dir)) return out;
	const walk = (d: string) => {
		for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
			const full = path.join(d, entry.name);
			if (entry.isDirectory()) walk(full);
			else if (entry.name.endsWith(".yaml")) {
				const rel = path.relative(dir, full).replace(/\.yaml$/, "");
				out[keyFn(rel)] = fs.readFileSync(full, "utf-8");
			}
		}
	};
	walk(dir);
	return out;
}

function build(): {
	version: string;
	workflows: Record<string, string>;
	resources: Record<string, string>;
	routes: Record<string, string>;
	navigation: string | null;
} {
	const root = resolveCatalogRoot();
	if (!root) {
		console.warn("console catalogue source not found; emitting empty catalogue");
		return { version: "unavailable", workflows: {}, resources: {}, routes: {}, navigation: null };
	}
	const catalog = path.join(root, "catalog");
	// workflows keyed "<resource>/<operation>" (directory/file)
	const workflows = readYamlDir(path.join(catalog, "workflows"), rel => rel.split(path.sep).join("/"));
	// resources/routes keyed by basename id
	const resources = readYamlDir(path.join(catalog, "resources"), rel => path.basename(rel));
	const routes = readYamlDir(path.join(catalog, "routes"), rel => path.basename(rel));
	const navPath = path.join(catalog, "navigation/console-tree.yaml");
	const navigation = fs.existsSync(navPath) ? fs.readFileSync(navPath, "utf-8") : null;
	const version = process.env.CONSOLE_CATALOG_VERSION ?? "local";
	return { version, workflows, resources, routes, navigation };
}

const data = build();

// Fix A: when the source was not found AND the output file already exists,
// keep the committed catalogue rather than overwriting it with empty data.
if (data.version === "unavailable" && fs.existsSync(outputPath)) {
	console.log("console catalogue source not found; keeping existing generated module");
	process.exit(0);
}

const output = [
	"// Auto-generated by scripts/generate-console-catalog.ts - DO NOT EDIT",
	"",
	`import type { ConsoleCatalogData } from "./console-catalog-types";`,
	"",
	`export const CONSOLE_CATALOG_VERSION = ${JSON.stringify(data.version)};`,
	"",
	`export const CONSOLE_CATALOG_DATA: ConsoleCatalogData = ${JSON.stringify(data, null, 2)};`,
	"",
].join("\n");

await Bun.write(outputPath, output);
console.log(
	`Wrote ${outputPath} (workflows=${Object.keys(data.workflows).length}, resources=${Object.keys(data.resources).length})`,
);
