#!/usr/bin/env bun

import { Database } from "bun:sqlite";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, utimes, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { gzipSync } from "node:zlib";
import { createStore } from "@tobilu/qmd";
import {
	buildApiCatalogDiscoveryCorpus,
	fingerprintApiCatalogDiscoveryCorpus,
} from "../src/internal-urls/api-catalog-discovery";
import { API_CATALOG_DATA, API_CATALOG_INDEX } from "../src/internal-urls/api-catalog-index.generated";

const sourceSha = "04e4dbd8245c527a88f1a8f0bda547aef9ca81fb";
const qmdVersion = "2.8.3";
const outputPath = path.join(import.meta.dir, "../src/internal-urls/api-catalog-qmd-index.generated.ts");

function sha256(bytes: Uint8Array): string {
	return createHash("sha256").update(bytes).digest("hex");
}

function canonicalizeSqliteMetadata(databasePath: string): void {
	const database = new Database(databasePath);
	try {
		database.exec("BEGIN");
		database.prepare("UPDATE content SET created_at = ?").run("2000-01-01T00:00:00.000Z");
		database
			.prepare("UPDATE documents SET created_at = ?, modified_at = ?")
			.run("2000-01-01T00:00:00.000Z", "2000-01-01T00:00:00.000Z");
		database.prepare("UPDATE store_collections SET path = ?").run("/xcsh-api-catalog");
		database.exec("DELETE FROM store_config");
		database.exec("COMMIT");
		database.exec("VACUUM");
	} finally {
		database.close();
	}
}

const corpus = buildApiCatalogDiscoveryCorpus(API_CATALOG_INDEX, API_CATALOG_DATA);
const fingerprint = fingerprintApiCatalogDiscoveryCorpus(corpus, sourceSha, `@tobilu/qmd@${qmdVersion}`);
const stagingRoot = await mkdtemp(path.join(os.tmpdir(), "xcsh-qmd-index-"));
const documentsRoot = path.join(stagingRoot, "documents");
const databasePath = path.join(stagingRoot, "index.sqlite");
const fixedDocumentTime = new Date("2000-01-01T00:00:00.000Z");

try {
	await mkdir(documentsRoot, { recursive: true });
	for (const document of corpus.documents) {
		const documentPath = path.join(documentsRoot, `${document.categoryName}.md`);
		await writeFile(documentPath, document.markdown, "utf8");
		await utimes(documentPath, fixedDocumentTime, fixedDocumentTime);
	}
	const store = await createStore({
		dbPath: databasePath,
		config: { collections: { catalog: { path: documentsRoot, pattern: "*.md" } } },
	});
	try {
		await store.update();
	} finally {
		await store.close();
	}
	canonicalizeSqliteMetadata(databasePath);
	const sqlite = await readFile(databasePath);
	const gzip = gzipSync(sqlite);
	const generated = [
		"// Generated by scripts/generate-api-catalog-qmd-index.ts. Do not edit.",
		`export const QMD_API_CATALOG_PREBUILT_INDEX = ${JSON.stringify({
			fingerprint,
			sqliteSha256: sha256(sqlite),
			gzipBase64: gzip.toString("base64"),
		})} as const;`,
		"",
	].join("\n");
	await writeFile(outputPath, generated, "utf8");
	console.log(
		`Generated ${path.relative(process.cwd(), outputPath)} (${sqlite.length} SQLite bytes, ${gzip.length} gzip bytes)`,
	);
} finally {
	await rm(stagingRoot, { recursive: true, force: true });
}
