import { createKindResolver } from "@f5-sales-demo/pi-resource-management";
import { API_SPEC_INDEX, API_VALIDATION_DATA } from "../internal-urls/api-spec-index.generated";

export const kindResolver = createKindResolver(API_SPEC_INDEX, API_VALIDATION_DATA);

export type {
	ApiSpecDomainEntry,
	ApiSpecDomainResource,
	ApiSpecIndex,
	ApiSpecValidationResourceEntry,
	DiffEntry,
	KindResolver,
	ManifestOperationInput,
	ManifestValidationResult,
	OperationResult,
	ParsedResourceArgs,
	ResolvedKind,
	ResourceClientOptions,
	ResourceDiff,
	ResourceError,
	ResourceManifest,
	ResourceOperation,
	ResourceOperationCounts,
	ResourceOperationItem,
	ResourceOperationReport,
	ValidationError,
	ValidationWarning,
} from "@f5-sales-demo/pi-resource-management";
export {
	computeResourceDiff,
	createKindResolver,
	formatDiff,
	formatMultiOperationSummary,
	formatOperationResult,
	formatResourceDetail,
	formatResourceList,
	formatResourceOperationReport,
	formatValidationErrors,
	KindResolutionError,
	ManifestFileError,
	ManifestParseError,
	parseManifests,
	parseResourceArgs,
	ResourceClient,
	readManifestFiles,
	readManifestInputs,
	runResourceOperation,
	validateManifest,
	validateManifests,
} from "@f5-sales-demo/pi-resource-management";
