import {expect,test} from "bun:test";import {parseProviderIdentity,identityTokens} from "./provider-identity-parser";
test("provider spans retain unknown and malformed identities without choosing prose alternatives",()=>{for(const q of ["Do not modify state for xcsh_missing_fixture resource like origin pool","xcsh_missing_fixture (resource)","resource named \"xcsh_missing_fixture\"","xcsh_missing_fixture.instance"]){expect(parseProviderIdentity(q).providerNames).toEqual(["missing_fixture"]);}expect(parseProviderIdentity("xcsh_123widget resource").identities[0]?.valid).toBe(false);expect(parseProviderIdentity("xcsh_missing-widget resource").identities[0]?.valid).toBe(false);});
test("variables functions quotedvalues and rejected identities retain classified evidence",()=>{for(const q of ["env.XCSH_REGION","var.xcsh_region","xcsh_helper ()","description is \"xcsh_missing_fixture\"","description is \x27xcsh_missing_fixture\x27","not xcsh_missing_fixture"]){expect(parseProviderIdentity(q).providerNames).toEqual([]);expect(parseProviderIdentity(q).identities).toHaveLength(1);}expect(parseProviderIdentity("Do not use xcsh_origin_pool but find xcsh_missing_fixture resource").providerNames).toEqual(["missing_fixture"]);});
test("explicit roles exclude quotes and rejectedroles while ephemeralresource is one role",()=>{for(const q of ["xcsh_origin_pool resource not a data source","xcsh_origin_pool resource excluding data source","xcsh_origin_pool resource description is \"xcsh_missing data source\"","xcsh_origin_pool resource label is \x27data source\x27"]){expect(parseProviderIdentity(q).explicitRole).toBe("resources");}expect(parseProviderIdentity("ephemeral resource xcsh_fixture").explicitRole).toBe("ephemeral-resources");expect(parseProviderIdentity("resource or data source xcsh_fixture").conflictingRoles).toBe(true);});
test("token spans refer to original string without deleting quoted or Unicodecontent",()=>{const text="界 \"xcsh_fixture\" resource";for(const t of identityTokens(text)){expect(text.slice(t.start,t.end).toLowerCase()).toBe(t.text);}});

test("apostrophes inside a quotation do not expose quoted values as identities",()=>{expect(parseProviderIdentity("description is \"owner\x27s xcsh_missing_fixture\"").providerNames).toEqual([]);expect(parseProviderIdentity("description is \"owner\x27s data source\"; xcsh_fixture resource").explicitRole).toBe("resources");});
test("example scope ends at sentence boundary and affirmative role resumes after but",()=>{expect(parseProviderIdentity("For example xcsh_sample. Find xcsh_missing_fixture resource").providerNames).toEqual(["missing_fixture"]);expect(parseProviderIdentity("not a data source but resource xcsh_fixture").explicitRole).toBe("resources");});

test("environmentlabels and data instance syntax carry correct identity kinds androles",()=>{expect(parseProviderIdentity("Use xcsh_region environment variable").providerNames).toEqual([]);expect(parseProviderIdentity("Read data.xcsh_origin_pool.example").explicitRole).toBe("data-sources");});
