// Generated by scripts/generate-documentation-index.ts for compiled builds. Do not edit.
import indexGzipPath from "./.documentation-generated/documentation-index.sqlite.gz" with { type: "file" };
import archivePath from "./.documentation-generated/html-to-markdown-content.tar.gz" with { type: "file" };
import type { EmbeddedDocumentationAssets } from "./documentation-repository";
export const EMBEDDED_DOCUMENTATION_ASSETS = {
	archivePath,
	indexGzipPath,
	indexGzipSha256: "1c24e5875a107d0d310be2e883c44543573de4468ba3fae6bc53abafae2beebd",
	indexGzipSizeBytes: 9806600,
	releaseTag: "content-20260928T015140Z",
	sourceCommit: "a2ca3b5c9c97bad5a2f40c71050c0951cc4148ed",
	archiveSha256: "1aa5edc65c8364667b82cd2f660ab4066fe8a93af0aa16d6ebde7c728be527fa",
	archiveSizeBytes: 174194845,
	indexSha256: "e34df7b6a14186d6d07eba545764f8ff7e81cd6efe1a97928952239fee6a5f3b",
	indexSizeBytes: 34062336,
	fingerprint: "cf8e58dc97c5b4ead742ca3c0d4f9ad6c21768faee61b03eb03759abcbbf6de1",
	documentCount: 1063,
	assetCount: 2825,
} as const satisfies EmbeddedDocumentationAssets;
