// Generated by scripts/generate-documentation-index.ts for compiled builds. Do not edit.
import type { EmbeddedDocumentationAssets } from "./documentation-repository";
export const EMBEDDED_DOCUMENTATION_ASSETS: EmbeddedDocumentationAssets | null = null;
