// Generated by scripts/generate-documentation-index.ts for compiled builds. Do not edit.
import indexGzipPath from "./.documentation-generated/documentation-index.sqlite.gz" with { type: "file" };
import type { EmbeddedDocumentationAssets } from "./documentation-repository";
export const EMBEDDED_DOCUMENTATION_ASSETS = {
	indexGzipPath,
	indexGzipSha256: "424efe7a0d82bc5bc2bf0b22371acca1a169cef614130600476a98f302debe78",
	indexGzipSizeBytes: 12975675,
	releaseTag: "content-20261007T031703Z",
	sourceCommit: "dd073238958c0c86b3c898c0a20eb3fb8cfc188c",
	archiveSha256: "4ae579770beaac82b483c92e44844e4d0e4ba3a03b0b2efaccbaf3c5a84b2d88",
	archiveSizeBytes: 567396491,
	indexSha256: "9ce6605024724cc9a5b9ad0ab1ecad533c290d00609e734e7fe0d47440952026",
	indexSizeBytes: 44793856,
	fingerprint: "7d73c415db742d726539ce04353841d2ad0479bbf26040ed901785027ee2f2d0",
	documentCount: 715,
	assetCount: 3556,
	textManifestSha256: "dccf724488c27187a4e805e730c1e5954f5db0ebe9608dd94618ce3757e59824",
	bundledAssetCount: 0,
} as const satisfies EmbeddedDocumentationAssets;
