#!/usr/bin/env bun

const packageRoot = new URL("../", import.meta.url);
const cssPath = new URL("node_modules/temml/dist/Temml-Local.css", packageRoot);
const fontPath = new URL("node_modules/temml/dist/Temml.woff2", packageRoot);
const outputPath = new URL("src/markdown/temml-css.generated.ts", packageRoot);

const upstreamCss = await Bun.file(cssPath).text();
const fontBytes = await Bun.file(fontPath).arrayBuffer();
const fontData = Buffer.from(fontBytes).toString("base64");
const withoutFontFace = upstreamCss.replace(/@font-face\s*\{[\s\S]*?\}\s*/, "");
const scopedRules = withoutFontFace.replace(
	/\bbody\s*\{\s*counter-reset:\s*tmlEqnNo;\s*\}/,
	":scope { counter-reset: tmlEqnNo; }",
);
const css =
	"@font-face{font-family:'Temml';src:url(data:font/woff2;base64," +
	fontData +
	") format('woff2');font-weight:normal;font-style:normal;}" +
	"@scope (.markdown-root){" +
	scopedRules +
	"}";
const output =
	"// Auto-generated by scripts/generate-temml-css.ts - DO NOT EDIT\n" +
	"export const TEMML_CSS = " +
	JSON.stringify(css) +
	";\n";

await Bun.write(outputPath, output);
console.log("Generated src/markdown/temml-css.generated.ts");
