#!/usr/bin/env bun

import * as path from "node:path";
import { $ } from "bun";
import { buildDeterministicArchiveBase64 } from "../../../scripts/deterministic-tar-gzip";

const GENERATED_FILE = path.join("src", "embedded-client.generated.txt");
const DIST_CLIENT_DIR = path.join("dist", "client");

const GENERATE_FLAG = "--generate";
const RESET_FLAG = "--reset";

function placeholderContent(): string {
	return `/**
 * Embedded stats dashboard bundle for compiled binaries.
 *
 * This file is generated by \`bun --cwd=packages/stats scripts/generate-client-bundle.ts --generate\` during
 * binary builds. The checked-in value is intentionally empty.
 */
export const EMBEDDED_CLIENT_ARCHIVE_TAR_GZ_BASE64 = "";
`;
}

async function main(): Promise<void> {
	if (process.argv.includes(RESET_FLAG)) {
		await Bun.write(GENERATED_FILE, placeholderContent());
		console.log(`Reset ${GENERATED_FILE}`);
		return;
	}

	if (!process.argv.includes(GENERATE_FLAG)) {
		console.log(`Skipping ${GENERATED_FILE}; pass ${GENERATE_FLAG} to build the embedded bundle`);
		return;
	}

	await $`bun run build`;
	const archiveBase64 = await buildDeterministicArchiveBase64(DIST_CLIENT_DIR);
	await Bun.write(GENERATED_FILE, archiveBase64);
	console.log(`Generated ${GENERATED_FILE}`);
}

await main();
