// AUTO-GENERATED by scripts/generate-defaults.ts — DO NOT EDIT BY HAND.
// Per-kind defaults knowledge for minimum-settings export. Regenerate with: bun run generate-defaults
// Source: NONE FOUND — empty table (kinds export everything until api-specs-enriched publishes minimal-export-defaults.json).
import type { KindDefaultsMetadata } from "./defaults-metadata";

export const DEFAULTS_METADATA: Record<string, KindDefaultsMetadata> = {};
